server:
  port: 9077
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  application:
    name: aiAgent

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG

