/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElementFormC: typeof import('./../src/components/globalComponents/ElementFormC/index.vue')['default']
    ElementTableC: typeof import('./../src/components/globalComponents/ElementTableC/index.vue')['default']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    MessageNotification: typeof import('./../src/components/MessageNotification/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubColumn: typeof import('./../src/components/globalComponents/ElementTableC/subColumn.vue')['default']
    ThreeLevelCheckBox: typeof import('./../src/components/threeLevelCheckBox/index.vue')['default']
  }
}
