/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElementFormC: typeof import('./../src/components/globalComponents/ElementFormC/index.vue')['default']
    ElementTableC: typeof import('./../src/components/globalComponents/ElementTableC/index.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubColumn: typeof import('./../src/components/globalComponents/ElementTableC/subColumn.vue')['default']
    ThreeLevelCheckBox: typeof import('./../src/components/threeLevelCheckBox/index.vue')['default']
  }
}
